name: doc-gen

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2 
    
    - name: Doxygen Action
      uses: mattnotmitt/doxygen-action@v1
      with:
           working-directory: 'openoffload/cpp/framework'
           doxyfile-path: 'doc/Doxyfile'
           
    - name: Generate archive
      uses: actions/upload-artifact@v2
      with:
          name: doxgen archive
          path: openoffload/cpp/framework/doc/html
      if: always()

    - name: Deploy to github Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: openoffload/cpp/framework/doc/html

